[package]
name = "diaryx-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"]}
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
